// Firebase Hosting rewrites (see firebase.json) send /room/:code and
// /room/:code/og-image.png here instead of the static SPA shell, so a link
// unfurler (or a human visitor) sees the actual room code and theming
// without executing any JS. Every other route still falls through to the
// static dist/index.html.
import { onRequest } from 'firebase-functions/v2/https'
import { initializeApp } from 'firebase-admin/app'
import { getFirestore } from 'firebase-admin/firestore'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import sharp from 'sharp'
import { buildOgImageSvg } from './og-image.js'

initializeApp()
const db = getFirestore()

const __dirname = path.dirname(fileURLToPath(import.meta.url))
// Generated by scripts/copy-index-template.mjs from the built dist/index.html
// as a Hosting predeploy step — see that script and firebase.json.
const indexTemplate = readFileSync(path.join(__dirname, 'index-template.html'), 'utf8')

const SITE_NAME = 'UNO Online'
const DEFAULT_DESCRIPTION = 'Real-time multiplayer UNO — create a room, share the code, and play with friends.'

// Same whitelist as src/lib/room.js's CODE_CHARS (no 0/O/1/I) — anything
// else in the URL just means no matching room, not a malformed request.
const CODE_RE = /^\/room\/([A-Za-z0-9]{3,10})/

function escapeHtml(str) {
  return String(str).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c])
}

async function lookupRoom(code) {
  if (!code) return null
  try {
    const snap = await db.collection('rooms').doc(code).get()
    return snap.exists ? snap.data() : null
  } catch {
    // Firestore hiccup — callers fall back to generic copy rather than fail
    // the whole request over what's just a cosmetic preview.
    return null
  }
}

function modeLabel(room) {
  return room?.mode === 'no-mercy' ? 'UNO No Mercy' : 'Classic UNO'
}

export const renderRoom = onRequest({ region: 'us-central1' }, async (req, res) => {
  const match = req.path.match(CODE_RE)
  const code = match ? match[1].toUpperCase() : ''
  const room = await lookupRoom(code)

  const origin = `${req.protocol}://${req.get('host')}`
  const title = code ? `Join room ${code} — ${SITE_NAME}` : SITE_NAME
  const playerCount = Array.isArray(room?.players) ? room.players.length : null
  const description = code
    ? `${modeLabel(room)} room ${code}${playerCount ? ` · ${playerCount} player${playerCount === 1 ? '' : 's'} in` : ''} — tap to join.`
    : DEFAULT_DESCRIPTION
  const imageUrl = code ? `${origin}/room/${code}/og-image.png` : `${origin}/og-image.png`
  const pageUrl = `${origin}${req.originalUrl}`

  const metaBlock = `<!-- og:meta:start -->
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="${SITE_NAME}" />
    <meta property="og:title" content="${escapeHtml(title)}" />
    <meta property="og:description" content="${escapeHtml(description)}" />
    <meta property="og:url" content="${escapeHtml(pageUrl)}" />
    <meta property="og:image" content="${escapeHtml(imageUrl)}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escapeHtml(title)}" />
    <meta name="twitter:description" content="${escapeHtml(description)}" />
    <meta name="twitter:image" content="${escapeHtml(imageUrl)}" />
    <!-- og:meta:end -->`

  const html = indexTemplate
    .replace(/<title>.*?<\/title>/, `<title>${escapeHtml(title)}</title>`)
    .replace(/<!-- og:meta:start -->[\s\S]*?<!-- og:meta:end -->/, metaBlock)

  // Short max-age: a room's player count (part of the description) changes
  // as people join, and a code gets reused once its room is gone.
  res.set('Cache-Control', 'public, max-age=60, s-maxage=300')
  res.set('Content-Type', 'text/html; charset=utf-8')
  res.status(200).send(html)
})

export const ogImage = onRequest({ region: 'us-central1' }, async (req, res) => {
  const match = req.path.match(/^\/room\/([A-Za-z0-9]{3,10})\/og-image\.png/)
  const code = match ? match[1].toUpperCase() : ''
  const room = await lookupRoom(code)

  const svg = buildOgImageSvg({ code, subtitle: code ? modeLabel(room) : '' })
  const png = await sharp(Buffer.from(svg)).png().toBuffer()

  res.set('Cache-Control', 'public, max-age=300, s-maxage=3600')
  res.set('Content-Type', 'image/png')
  res.status(200).send(png)
})
